### ISSUE TITLE
Serial module only has one input and output

### ISSUE THREAD

**Issue by GreatWhiteDan** [sahajquinci/simplewmqttclient#2]
Sorry if I am just misunderstanding the usage on serial.   For both analog and digital there is a separate digital or analog input/output per topic, but on serial there is only one.   Could be an issue with the code, or I may just misunderstand.   Thank you for your hard work on this.  It is a greatly needed capability.

Screenshot:
https://imgur.com/a/nLepbGB

**Comment by GreatWhiteDan** [comment]
Additional information, if I manually edit the String, Input, and output parameters that are set to auto expand to 255 and set them to say [255,20] and compile, the system show the module properly with the input output and string fields and works, but even then, if you expand it, it runs into the same issue.  This appears to be the case on all three modules, at least in version 4.17 of SIMPL.  I was going to try an older version but I only have 4.10 and 4.11 not 4.14 and the download link on crestron is broken.

**Comment by sahajquinci** [comment]
Hi,
sadly, I do not work with Crestron software for a while already, but you are the first person who is raising this issue. Is this the case for the available Demos as well?
My Suggestion would be to try to fix the simpl+ module definition and then simply recompile it. All the Simpl# should still work with no issues.

**Comment by GreatWhiteDan** [comment]
Thank you for responding, and yes, I figured out the issue, just yesterday.  It was an user issue on my side.  I kept adding the symbols on the text input line instead of on the input/output lines.   Not sure how I have never ran into that before, but when I started adding the additional lines on the right spot it is working perfectly.   Thanks for making a great module.
