### ISSUE TITLE
A "dot" (.) in topic raises an error

### ISSUE THREAD

**Issue by Bagunda** [sahajquinci/simplewmqttclient#3]
I wanted to use a topic "Crestron/MR4/CR-IP11-VIP1-CN22-LN01-ID-04-KL.1.011" or "Crestron/MR4/CR-IP11-VIP1-DALI_iP41".
And a "dot" (.) and "_" in mqtt topic raises an error.
P.S. Maybe two dots in topic rase an error.
ErrorOccured: ArgumentOutOfRangeException

Offtopic: 255 fields for signals - too few.
However, thanks for the program!

![image](https://user-images.githubusercontent.com/16766521/144992670-18cbdc7e-1bab-40f5-b594-4d54b1ba2e45.png)

![image](https://user-images.githubusercontent.com/16766521/145006987-ffa4d75e-6004-4282-80f3-9177a1a1969f.png)

**Comment by Bagunda** [comment]
And this topic resi error:
"Crestron/MR4/CR-IP11-VIP1-CN21-LN01-ID-03-DimmerD1"
And this work norm:
"Crestron/MR4/CR-IP11-VIP1-CN21-LN01-ID-03-Dimmerd1"

**Comment by sahajquinci** [comment]
Hi Sorry to get back to late.

Development on this module is completely ended. You can increase the number of topics by increasing the value in simpl+ and recompiling.
For the topic names you should look in the code where a topic name is parsed or where it is sent. One of those two places is likely to have a bug.
Same here though you can fix it and recompile it
