### ISSUE TITLE
MQTT Message are sent Retained Alltime

### ISSUE THREAD

**Issue by Hollako** [sahajquinci/simplewmqttclient#4]
Hello,

First, thanks for the effort.

I am testing the module and everything goes very well. then I noticed that the messages are sent retained all-time regardless if I put Retain False or True.

Any idea bout this issue?

**Comment by sahajquinci** [comment]
Hi, sorry for the late reply, sadly I don't remember the logic as it has been a long time, but [here](https://github.com/sahajquinci/simplewmqttclient/blob/2751d17e9028c2dd7c5605fdd1bcf64040e38ad8/sahajquinci.MQTT_Client/MqttClient.cs#L118)
is where this value is set.
Have you tried using WillRetain ?

**Comment by Hollako** [comment]
Hello,

Actually, I did try all the options without success all the retains are false, moreover I noticed that you made a fix for this problem but maybe the .clz files are not updated with this fix. Cause as I noticed in the fix done that the Retain flag was always "true" and not a variable "Retain".

**Comment by sahajquinci** [comment]
Ok, then you simply need to recompile the source code files 🙂

**Comment by Hollako** [comment]
Well Noted, Thank you !!
