### ISSUE TITLE
Problem of connection

### ISSUE THREAD

**Issue by OZEO-DOOZ** [sahajquinci/simplewmqttclient#5]
Hi,

I have this kind of logs :

L:01 [2022-05-25 22:47:58]: MQTTCLIENT - Connect , attempting connection to 192.168.1.30
L:01 [2022-05-25 22:47:58]: MQTTCLIENT - OnSocketStatusChange - DIGITAL socket status : SOCKET_STATUS_CONNECTED
L:02 [2022-05-25 22:47:58]: MQTTCLIENT - SEND - Sending packet :CONNECT(protocolName:MQTT,protocolVersion:4,clientId:12345,willFlag:False,willRetain:False,willQosLevel:0,willTopic:disconnection,willMessage:Digital Died,username://,password://,cleanSession:False,keepAlivePeriod:10000)
L:01 [2022-05-25 22:47:58]: MQTTCLIENT - OnSocketStatusChange - DIGITAL socket status : SOCKET_STATUS_NO_CONNECT
L:07 [2022-05-25 22:47:58]: MQTTCLIENT - ConnectToServerCallback - Error occured : First byte shifted : 0
L:07 [2022-05-25 22:47:58]: MQTTCLIENT - ConnectToServerCallback - Error occured : at sahajquinci.MQTT_Client.Utility.PacketDecoder.DecodeControlPacket(Byte[] data)
at sahajquinci.MQTT_Client.MqttClient.ConnectToServerCallback(SecureTCPClient myTCPClient)
at Crestron.SimplSharp.CrestronSockets.SecureTCPClient.l(IAsyncResult A_0)
at System.Net.LazyAsyncResult.InvokeCallback(Boolean asyncCompletion)
at System.Net.Sockets.Socket.WorkerThread.doWork()
at System.Net.Sockets.Socket.WorkerThread.doWorkI(Object o)
at System.Threading.ThreadPool.WorkItem.doWork(Object o)
at System.Threading.Timer.ring()

Do you know where is the problem?

**Comment by sahajquinci** [comment]
Hi,
I see you are using the TLS version.
The secure is likely to have issues if there is no secure connection in place on the other side. It might also check for certificates, but can't be sure

If I were you I would use the NON TLS regular version
https://github.com/sahajquinci/simplewmqttclient/blob/master/MQTT_Client_DEMO%20NO%20TLS.rar
